### ISSUE TITLE
VCF conversion

### ISSUE THREAD

**Issue by RichardChinnis** [gaitat/GenomeUPlot#1]
Hi,

I attempted to use the Rscript to convert a VCF file and received the following error.  Did I miss a step, or is this VCF file not an appropriate candidate for conversion?

Error in data.frame(chrA, chrB, posA, posB) : 
  arguments imply differing number of rows: 4133148, 0
Calls: vcftocsvData -> data.frame
Execution halted

Thanks,

Richard

**Comment by gaitat** [comment]
Which VCF file are you referring to. The one supplied with the application?

**Comment by RichardChinnis** [comment]
No, my own personal VCF from an NGS I had done recently.  It's about 650MB, so rather massive.

**Comment by gaitat** [comment]
Did you try the provided VCF? Did that work for you?

**Comment by RichardChinnis** [comment]
I just tried it, and it did work, so there must be something gone awry with my VCF.
